import re

import pandas as pd

# ── Universal Text Cleaner (works on PDF, TXT, CSV text) ─────────────────────

# Common garbage patterns found in real-world documents
GARBAGE_PATTERNS = [
    r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]",  # control characters
    r"\ufffd",  # unicode replacement char
    r"_{3,}",  # long underscores (form fields)
    r"-{3,}",  # long dashes (separators)
    r"\*{3,}",  # long asterisks
    r"={3,}",  # long equals
    r"\.{4,}",  # long dots (table of contents)
    r"\s{3,}",  # excessive whitespace → single space
]

# Common boilerplate phrases to remove from documents (literal substrings)
BOILERPLATE_LITERALS = [
    "this page intentionally left blank",
    "confidential and proprietary",
    "all rights reserved",
    "printed on",
    "generated by",
    "powered by",
    "watermark",
    "draft copy",
    "do not distribute",
]

# Regex-only boilerplate (e.g. pagination lines)
BOILERPLATE_REGEX = [
    r"page \d+ of \d+",
]


def clean_universal_text(text: str) -> str:
    """
    Universal text cleaner for any document type (PDF, TXT, CSV).
    Removes garbage characters, normalizes whitespace, strips boilerplate.
    """
    if not text:
        return ""

    # Remove control characters and garbage unicode
    for pattern in GARBAGE_PATTERNS[:7]:  # skip whitespace pattern — handle separately
        text = re.sub(pattern, " ", text)

    # Remove boilerplate phrases
    for phrase in BOILERPLATE_LITERALS:
        text = re.sub(re.escape(phrase), "", text, flags=re.IGNORECASE)
    for pat in BOILERPLATE_REGEX:
        text = re.sub(pat, "", text, flags=re.IGNORECASE)

    # Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Remove excessive blank lines (more than 2 in a row)
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Normalize whitespace within lines
    lines = []
    for line in text.split("\n"):
        line = re.sub(r"[ \t]+", " ", line).strip()
        lines.append(line)
    text = "\n".join(lines)

    return text.strip()


def clean_pdf_text(text: str) -> str:
    """
    PDF-specific cleaner — handles common PDF extraction artifacts.
    """
    if not text:
        return ""

    # Fix common PDF extraction issues
    text = re.sub(r"([a-z])([A-Z])", r"\1 \2", text)  # fix merged words: helloWorld → hello World
    text = re.sub(r"(\w)-\n(\w)", r"\1\2", text)  # fix hyphenated line breaks
    text = re.sub(r"\n([a-z])", r" \1", text)  # fix broken sentences across lines
    text = re.sub(r"[^\S\n]+", " ", text)  # normalize spaces (not newlines)

    # Remove page numbers standing alone on a line
    text = re.sub(r"^\s*\d+\s*$", "", text, flags=re.MULTILINE)

    # Remove common PDF header/footer artifacts
    text = re.sub(r"^\s*(Page|PAGE)\s+\d+.*$", "", text, flags=re.MULTILINE)

    return clean_universal_text(text)


def clean_txt_text(text: str) -> str:
    """
    TXT-specific cleaner — handles plain text artifacts.
    """
    if not text:
        return ""

    # Fix Windows line endings
    text = text.replace("\r\n", "\n")

    # Remove null bytes
    text = text.replace("\x00", "")

    # Fix common encoding issues
    text = text.replace("\u2019", "'")  # smart apostrophe
    text = text.replace("\u201c", '"')  # smart left quote
    text = text.replace("\u201d", '"')  # smart right quote
    text = text.replace("\u2013", "-")  # en dash
    text = text.replace("\u2014", "--")  # em dash

    return clean_universal_text(text)


def clean_csv_text_output(text: str) -> str:
    """
    Clean the text output of a CSV dataframe (after converting to string).
    """
    if not text:
        return ""

    # Remove NaN values that pandas leaves in text output
    text = re.sub(r"\bnan\b", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\bNone\b", "", text)
    text = re.sub(r"\bNaT\b", "", text)

    return clean_universal_text(text)


def clean_csv_row(row: dict) -> dict:
    """Normalize cell values for downstream structured extraction."""
    cleaned: dict = {}
    for k, v in row.items():
        key = k.strip() if isinstance(k, str) else k
        if v is None:
            cleaned[key] = None
            continue
        try:
            if pd.isna(v):
                cleaned[key] = None
                continue
        except TypeError:
            pass

        if isinstance(v, bool):
            cleaned[key] = v
            continue
        if isinstance(v, (int, float)):
            cleaned[key] = v
            continue

        if hasattr(v, "item"):
            try:
                v = v.item()
            except (ValueError, AttributeError):
                pass
            try:
                if pd.isna(v):
                    cleaned[key] = None
                    continue
            except TypeError:
                pass
            if isinstance(v, bool):
                cleaned[key] = v
                continue
            if isinstance(v, (int, float)):
                cleaned[key] = v
                continue

        s = str(v).strip()
        s = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]", "", s)
        cleaned[key] = s if s else None

    # Light normalization for department-style columns
    for dk in list(cleaned.keys()):
        if dk and isinstance(dk, str) and "department" in dk.lower():
            val = cleaned.get(dk)
            if isinstance(val, str):
                cleaned[dk] = re.sub(r"\s+", " ", val).strip() or None

    return cleaned


def get_cleaning_stats(original_rows: list, cleaned_rows: list) -> dict:
    """Summarize how many rows changed after clean_csv_row."""
    n = min(len(original_rows), len(cleaned_rows))
    if n == 0:
        return {"rows_processed": 0, "rows_modified": 0}
    changed = sum(
        1 for i in range(n) if original_rows[i] != cleaned_rows[i]
    )
    return {
        "rows_processed": len(cleaned_rows),
        "rows_modified": changed,
    }


def get_text_quality_score(text: str) -> float:
    """
    Score text quality from 0.0 to 1.0 based on cleanliness indicators.
    Used to set confidence adjustments in the AI layer.
    """
    if not text:
        return 0.0

    total_chars = len(text)
    if total_chars == 0:
        return 0.0

    # Count problematic patterns
    garbage_chars = len(re.findall(r"[\x00-\x1f\x7f-\x9f]", text))
    repeated_chars = len(re.findall(r"(.)\1{4,}", text))  # chars repeated 5+ times
    all_caps_words = len(re.findall(r"\b[A-Z]{4,}\b", text))
    normal_words = len(re.findall(r"\b[a-zA-Z]{2,}\b", text))

    # Penalize garbage
    garbage_ratio = garbage_chars / total_chars
    caps_ratio = all_caps_words / max(normal_words, 1)

    score = 1.0
    score -= min(garbage_ratio * 10, 0.3)  # up to -0.3 for garbage chars
    score -= min(caps_ratio * 0.2, 0.2)  # up to -0.2 for excessive caps
    score -= min(repeated_chars / total_chars * 5, 0.2)  # up to -0.2 for repetition

    return round(max(score, 0.0), 2)
